["github.com/BurntSushi/toml"]
  sumVersion = "v0.3.1"
  ["github.com/BurntSushi/toml".fetch]
    type = "git"
    url = "https://github.com/BurntSushi/toml"
    rev = "3012a1dbe2e4bd1391d42b32f0577cb7bbc7f005"
    sha256 = "1fjdwwfzyzllgiwydknf1pwjvy49qxfsczqx5gz3y0izs7as99j6"

["github.com/Songmu/gitconfig"]
  sumVersion = "v0.1.0"
  ["github.com/Songmu/gitconfig".fetch]
    type = "git"
    url = "https://github.com/Songmu/gitconfig"
    rev = "772c25c1c40d094d4003531570cd4929ce4f36ef"
    sha256 = "1y01h496a7pfj1g2bclls5b0nl3vnj7nz610jj1dzq9kxrwxk7fk"

["github.com/cpuguy83/go-md2man/v2"]
  sumVersion = "v2.0.0"
  ["github.com/cpuguy83/go-md2man/v2".fetch]
    type = "git"
    url = "https://github.com/cpuguy83/go-md2man"
    rev = "f79a8a8ca69da163eee19ab442bedad7a35bba5a"
    sha256 = "0r1f7v475dxxgzqci1mxfliwadcrk86ippflx9n411325l4g3ghv"

["github.com/davecgh/go-spew"]
  sumVersion = "v1.1.0"
  ["github.com/davecgh/go-spew".fetch]
    type = "git"
    url = "https://github.com/davecgh/go-spew"
    rev = "346938d642f2ec3594ed81d874461961cd0faa76"
    sha256 = "0d4jfmak5p6lb7n2r6yvf5p1zcw0l8j74kn55ghvr7zr7b7axm6c"

["github.com/daviddengcn/go-colortext"]
  sumVersion = "v1.0.0"
  ["github.com/daviddengcn/go-colortext".fetch]
    type = "git"
    url = "https://github.com/daviddengcn/go-colortext"
    rev = "dc4cd66b56a892657c0bea8bf4389d35210ce0ee"
    sha256 = "0j5ldwg3a768d3nniiglghr9axj4p87k7f7asqxa1a688xvcms48"

["github.com/fatih/color"]
  sumVersion = "v1.10.0"
  ["github.com/fatih/color".fetch]
    type = "git"
    url = "https://github.com/fatih/color"
    rev = "bc2269661d49c6c9d0e514eef49710556883f3fa"
    sha256 = "1azg1r8ifnr1pk5lvqkpcssqb7s7hs0zym1fmg0k67p842bvm2n8"

["github.com/go-playground/assert/v2"]
  sumVersion = "v2.0.1"
  ["github.com/go-playground/assert/v2".fetch]
    type = "git"
    url = "https://github.com/go-playground/assert"
    rev = "8eb943fbae8448cf47383208d8d0c396e26011a9"
    sha256 = "1cl9c4s405zddzrj36hhs0a18g02zscdl46fyipp6k91mhvai8wz"

["github.com/go-playground/locales"]
  sumVersion = "v0.13.0"
  ["github.com/go-playground/locales".fetch]
    type = "git"
    url = "https://github.com/go-playground/locales"
    rev = "9f105231d3a5f6877a2bf8321dfa15ea6f844b1b"
    sha256 = "0qydcpkvss3mf8mk3xzg6a34n8i69aydrigcl2apifrkx72jw7pf"

["github.com/go-playground/universal-translator"]
  sumVersion = "v0.17.0"
  ["github.com/go-playground/universal-translator".fetch]
    type = "git"
    url = "https://github.com/go-playground/universal-translator"
    rev = "f87b1403479a348651dbf5f07f5cc6e5fcf07008"
    sha256 = "1zdiaisb32iv4x93cpbqrgx8ll7sxh4hcd2iibpswy4bwvjbjlz6"

["github.com/go-playground/validator/v10"]
  sumVersion = "v10.4.1"
  ["github.com/go-playground/validator/v10".fetch]
    type = "git"
    url = "https://github.com/go-playground/validator"
    rev = "456221b630452990f72c0f13179e5f2ae728a723"
    sha256 = "0p4gs2wqa0wzdblhykk0pxrxmvl347hnjd5ws4nfh7bzn4kdnp11"

["github.com/goccy/go-yaml"]
  sumVersion = "v1.8.8"
  ["github.com/goccy/go-yaml".fetch]
    type = "git"
    url = "https://github.com/goccy/go-yaml"
    rev = "868d322819b933bce2a46cfa2951c08706600f14"
    sha256 = "128npaysha4wlwxgd41p9hvq4r5sxpg67ib6xfhgaais6jpx1d99"

["github.com/golangplus/bytes"]
  sumVersion = "v1.0.0"
  ["github.com/golangplus/bytes".fetch]
    type = "git"
    url = "https://github.com/golangplus/bytes"
    rev = "792249112b6ba0acca62a01807675f7e50a280f3"
    sha256 = "0r8f9m7hm6idnbapfb01nw5h09a20b09r7sky2gkniympn98ra75"

["github.com/golangplus/fmt"]
  sumVersion = "v1.0.0"
  ["github.com/golangplus/fmt".fetch]
    type = "git"
    url = "https://github.com/golangplus/fmt"
    rev = "7a904709ad79c030bc913f5d1d1823dcf3953fa4"
    sha256 = "07d5kxz0f8ss3v46y0c8jg02sagi0wlaaijhjzzp0r462jyzqii7"

["github.com/golangplus/testing"]
  sumVersion = "v1.0.0"
  ["github.com/golangplus/testing".fetch]
    type = "git"
    url = "https://github.com/golangplus/testing"
    rev = "d51138b619a0cd6d297e1a9985accd95ca75be46"
    sha256 = "1a29m4zplf9m14k74lrb55dids2l17vx28sv0g3y3qcv1xygksiv"

["github.com/leodido/go-urn"]
  sumVersion = "v1.2.0"
  ["github.com/leodido/go-urn".fetch]
    type = "git"
    url = "https://github.com/leodido/go-urn"
    rev = "a0f5013415294bb94553821ace21a1a74c0298cc"
    sha256 = "1d4g1vkhc1180l1n7q48vl84b27c7cziywml78cyijbcdz2f8vim"

["github.com/mattn/go-colorable"]
  sumVersion = "v0.1.8"
  ["github.com/mattn/go-colorable".fetch]
    type = "git"
    url = "https://github.com/mattn/go-colorable"
    rev = "2e1b0c1546e0173c0907cf05c67b8ba29ed8b4d1"
    sha256 = "0q34zqwbnls72md8q8mhj368s7p3i4xspvs3rk8fs76s0pn7dr2l"

["github.com/mattn/go-isatty"]
  sumVersion = "v0.0.12"
  ["github.com/mattn/go-isatty".fetch]
    type = "git"
    url = "https://github.com/mattn/go-isatty"
    rev = "7b513a986450394f7bbf1476909911b3aa3a55ce"
    sha256 = "1dfsh27d52wmz0nmmzm2382pfrs2fcijvh6cgir7jbb4pnigr5w4"

["github.com/motemen/go-colorine"]
  sumVersion = "v0.0.0-20180816141035-45d19169413a"
  ["github.com/motemen/go-colorine".fetch]
    type = "git"
    url = "https://github.com/motemen/go-colorine"
    rev = "45d19169413a019e4e2be69629dde5c7d92f8706"
    sha256 = "1mdy6q0926s1frj027nlzlvm2qssmkpjis7ic3l2smajkzh07118"

["github.com/pmezard/go-difflib"]
  sumVersion = "v1.0.0"
  ["github.com/pmezard/go-difflib".fetch]
    type = "git"
    url = "https://github.com/pmezard/go-difflib"
    rev = "792786c7400a136282c1664665ae0a8db921c6c2"
    sha256 = "0c1cn55m4rypmscgf0rrb88pn58j3ysvc2d0432dp3c6fqg6cnzw"

["github.com/russross/blackfriday/v2"]
  sumVersion = "v2.1.0"
  ["github.com/russross/blackfriday/v2".fetch]
    type = "git"
    url = "https://github.com/russross/blackfriday"
    rev = "4c9bf9512682b995722660a4196c0013228e2049"
    sha256 = "0d1rg1drrfmabilqjjayklsz5d0n3hkf979sr3wsrw92bfbkivs7"

["github.com/saracen/walker"]
  sumVersion = "v0.1.2"
  ["github.com/saracen/walker".fetch]
    type = "git"
    url = "https://github.com/saracen/walker"
    rev = "2c746f29c263bb7437b6b4870e577335eb4871e1"
    sha256 = "0xr39qk69wagqs7gdj96g8dp2j6d3w45xx360rpzvxfzf2ysvgkg"

["github.com/shurcooL/sanitized_anchor_name"]
  sumVersion = "v1.0.0"
  ["github.com/shurcooL/sanitized_anchor_name".fetch]
    type = "git"
    url = "https://github.com/shurcooL/sanitized_anchor_name"
    rev = "7bfe4c7ecddb3666a94b053b422cdd8f5aaa3615"
    sha256 = "1gv9p2nr46z80dnfjsklc6zxbgk96349sdsxjz05f3z6wb6m5l8f"

["github.com/stretchr/objx"]
  sumVersion = "v0.1.0"
  ["github.com/stretchr/objx".fetch]
    type = "git"
    url = "https://github.com/stretchr/objx"
    rev = "facf9a85c22f48d2f52f2380e4efce1768749a89"
    sha256 = "19ynspzjdynbi85xw06mh8ad5j0qa1vryvxjgvbnyrr8rbm4vd8w"

["github.com/stretchr/testify"]
  sumVersion = "v1.4.0"
  ["github.com/stretchr/testify".fetch]
    type = "git"
    url = "https://github.com/stretchr/testify"
    rev = "221dbe5ed46703ee255b1da0dec05086f5035f62"
    sha256 = "187i5g88sxfy4vxpm7dw1gwv29pa2qaq475lxrdh5livh69wqfjb"

["github.com/urfave/cli/v2"]
  sumVersion = "v2.3.0"
  ["github.com/urfave/cli/v2".fetch]
    type = "git"
    url = "https://github.com/urfave/cli"
    rev = "09ac54c2f97f4249282baf266c54a09fab1bef58"
    sha256 = "08pvn7gyfznni72xrxfh2x6xxa8ykr7l1ka278js8g8qkh71bj8l"

["golang.org/x/crypto"]
  sumVersion = "v0.0.0-20200622213623-75b288015ac9"
  ["golang.org/x/crypto".fetch]
    type = "git"
    url = "https://go.googlesource.com/crypto"
    rev = "75b288015ac94e66e3d6715fb68a9b41bf046ec2"
    sha256 = "18vlncvvs11ds3zaaziqjlg5s2vcwi3496nn6qv7p0dp94j5pwa2"

["golang.org/x/net"]
  sumVersion = "v0.0.0-20210224082022-3d97a244fca7"
  ["golang.org/x/net".fetch]
    type = "git"
    url = "https://go.googlesource.com/net"
    rev = "3d97a244fca747f9caeab9b98aa4302e662fb37b"
    sha256 = "16wjjq3w0kaddn8lsgrdhszmnbrfhj38lbymq0miq545f08xlvgx"

["golang.org/x/sync"]
  sumVersion = "v0.0.0-20210220032951-036812b2e83c"
  ["golang.org/x/sync".fetch]
    type = "git"
    url = "https://go.googlesource.com/sync"
    rev = "036812b2e83c0ddf193dd5a34e034151da389d09"
    sha256 = "1gl202py3s4gl6arkaxlf8qa6f0jyyg2f95m6f89qnfmr416h85b"

["golang.org/x/sys"]
  sumVersion = "v0.0.0-20210225014209-683adc9d29d7"
  ["golang.org/x/sys".fetch]
    type = "git"
    url = "https://go.googlesource.com/sys"
    rev = "683adc9d29d7bd1f0f778e1f7f2eeb61b415f4d5"
    sha256 = "1gnn2714vnm78k43abq0qlprfic6mai140xig65fmdj9z295s3vs"

["golang.org/x/term"]
  sumVersion = "v0.0.0-20201126162022-7de9c90e9dd1"
  ["golang.org/x/term".fetch]
    type = "git"
    url = "https://go.googlesource.com/term"
    rev = "7de9c90e9dd184706b838f536a1cbf40a296ddb7"
    sha256 = "1ba252xmv6qsvf1w1gcy98mngrj0vd4inbjw0lsklqvva65nljna"

["golang.org/x/text"]
  sumVersion = "v0.3.3"
  ["golang.org/x/text".fetch]
    type = "git"
    url = "https://go.googlesource.com/text"
    rev = "23ae387dee1f90d29a23c0e87ee0b46038fbed0e"
    sha256 = "19pihqm3phyndmiw6i42pdv6z1rbvlqlsnhsyqf9gsnn0qnmqqlh"

["golang.org/x/tools"]
  sumVersion = "v0.0.0-20180917221912-90fa682c2a6e"
  ["golang.org/x/tools".fetch]
    type = "git"
    url = "https://go.googlesource.com/tools"
    rev = "90fa682c2a6e6a37b3a1364ce2fe1d5e41af9d6d"
    sha256 = "03ic2xsy51jw9749wl7gszdbz99iijbd2bckgygl6cm9w5m364ak"

["golang.org/x/xerrors"]
  sumVersion = "v0.0.0-20200804184101-5ec99f83aff1"
  ["golang.org/x/xerrors".fetch]
    type = "git"
    url = "https://go.googlesource.com/xerrors"
    rev = "5ec99f83aff198f5fbd629d6c8d8eb38a04218ca"
    sha256 = "1dbzc3gmf2haazpv7cgmv97rq40g2xzwbglc17vas8dwhgwgwrzb"

["gopkg.in/check.v1"]
  sumVersion = "v0.0.0-20161208181325-20d25e280405"
  ["gopkg.in/check.v1".fetch]
    type = "git"
    url = "https://gopkg.in/check.v1"
    rev = "20d25e2804050c1cd24a7eea1e7a6447dd0e74ec"
    sha256 = "0k1m83ji9l1a7ng8a7v40psbymxasmssbrrhpdv2wl4rhs0nc3np"

["gopkg.in/go-playground/assert.v1"]
  sumVersion = "v1.2.1"
  ["gopkg.in/go-playground/assert.v1".fetch]
    type = "git"
    url = "https://gopkg.in/go-playground/assert.v1"
    rev = "4f4dfbc7d1c48336cf93399deae81aa9067e88af"
    sha256 = "1h4amgykpa0djwi619llr3g55p75ia0mi184h9s5zdl8l4rhn9pm"

["gopkg.in/go-playground/validator.v9"]
  sumVersion = "v9.30.0"
  ["gopkg.in/go-playground/validator.v9".fetch]
    type = "git"
    url = "https://gopkg.in/go-playground/validator.v9"
    rev = "cd1bd581694a11c089aea885a26247c5f783a4cf"
    sha256 = "1s9xlfadddl4fwzqs17xap0rk48cb3rwbrg9f0d08wjdm8yf4m1f"

["gopkg.in/yaml.v2"]
  sumVersion = "v2.2.3"
  ["gopkg.in/yaml.v2".fetch]
    type = "git"
    url = "https://gopkg.in/yaml.v2"
    rev = "bb4e33bf68bf89cad44d386192cbed201f35b241"
    sha256 = "0l2s7y180gkkvrmnw2xyfszz1m4kp92x2hz680c9vyklcbzsxrrx"
