[devshell]
packages = ["treefmt"]

[[commands]]
name = "CI-flake-show"
category = "tests"
command = '''
        sed -i 's|\# supportedSystems|supportedSystems|' flake.nix
        nix -Lv flake show
        git stash save --keep-index --include-untracked
        '''
help = "lock rev for bindary cache build"

[[commands]]
name = "nvfetcher-update"
category = "Update"
command = "nix develop -Lv 'github:GTrunSec/DevSecOps-Cells-Lab?dir=devshell#update' --no-write-lock-file -c nvfetcher-update ./packages/sources.toml"
help = "run nvfetcher with local repo's sources.toml"

[[commands]]
name = "nix-github-update"
category = "Update"
command = "nix develop -Lv 'github:GTrunSec/DevSecOps-Cells-Lab?dir=devshell#update' --no-write-lock-file -c nix-github-update"

[[commands]]
name = "packages-build"
category = "Build"
command = '''
        nix -Lv build .#broker --no-link
        nix -Lv build .#zed --no-link
        '''
help = "Build Packages with nix build"
