[devshell]
packages = ["treefmt"]

[[commands]]
name = "CI-flake-show"
category = "tests"
command = '''
        sed -i 's|\# supportedSystems|supportedSystems|' flake.nix
        nix -Lv flake show
        git stash save --keep-index --include-untracked
        '''
help = "lock rev for bindary cache build"

[[commands]]
name = "packages-build"
category = "Build"
command = '''
        nix -Lv build .#broker --no-link
        nix -Lv build .#zed --no-link
        '''
help = "Build Packages with nix build"
