schema = 3

[mod]
  [mod."github.com/agnivade/levenshtein"]
    version = "v1.1.1"
    hash = "sha256-tgv2s8XIcWjscv1pP87TOIUV4vADT2px1Lo/MQCTBjM="
  [mod."github.com/alecthomas/units"]
    version = "v0.0.0-20190717042225-c3de453c63f4"
    hash = "sha256-vho02JWLkLST8oBHdWufpXZxoDSkCUVkMP6M/eg/Q0s="
  [mod."github.com/apache/thrift"]
    version = "v0.16.0"
    hash = "sha256-4jsjTxU5CZ6feurBx3pIY2JF5FsoMewVOQHeVtgHkdA="
  [mod."github.com/araddon/dateparse"]
    version = "v0.0.0-20210429162001-6b43995a97de"
    hash = "sha256-UuX84naeRGMsFOgIgRoBHG5sNy1CzBkWPKmd6VbLwFw="
  [mod."github.com/aws/aws-sdk-go"]
    version = "v1.36.17"
    hash = "sha256-jUasRPchEoCFbnEAV1k61nxLRP9bynig/qriFeuLhQI="
  [mod."github.com/axiomhq/hyperloglog"]
    version = "v0.0.0-20191112132149-a4c4c47bc57f"
    hash = "sha256-mhThkWjecSomS8pP6uJDYnUq/isLLwhwsENXYKHvkl8="
  [mod."github.com/beorn7/perks"]
    version = "v1.0.1"
    hash = "sha256-h75GUqfwJKngCJQVE5Ao5wnO3cfKD9lSIteoLp/3xJ4="
  [mod."github.com/cespare/xxhash/v2"]
    version = "v2.1.1"
    hash = "sha256-cF+sDnnTZ1xRwjsy08SVSV/JoZalwY+dg0Zkghy6BNw="
  [mod."github.com/davecgh/go-spew"]
    version = "v1.1.1"
    hash = "sha256-nhzSUrE1fCkN0+RL04N4h8jWmRFPPPWbCuDc7Ss0akI="
  [mod."github.com/dgryski/go-metro"]
    version = "v0.0.0-20180109044635-280f6062b5bc"
    hash = "sha256-WdJuGgX7NKfocz6IhMcClfx30ZnxAPjfZTRAOr2eAqk="
  [mod."github.com/dgryski/go-rendezvous"]
    version = "v0.0.0-20200823014737-9f7001d12a5f"
    hash = "sha256-n/7xo5CQqo4yLaWMSzSN1Muk/oqK6O5dgDOFWapeDUI="
  [mod."github.com/fraugster/parquet-go"]
    version = "v0.10.1-0.20220222153523-e6b70a8a7212"
    hash = "sha256-eo9iwQHr1ox608jnuoYBtFmKxv923mg+H3KlECv9Iqk="
  [mod."github.com/go-redis/redis/v8"]
    version = "v8.4.11"
    hash = "sha256-+xxGAt4fAD8NO+W+CHFNPxqsqd5jIXeAWKRukxUu82o="
  [mod."github.com/golang-jwt/jwt"]
    version = "v3.2.1+incompatible"
    hash = "sha256-lRqMYMddv9J5IwqDBjqGmFtLpwwgvq86CkCvJxzM1cw="
  [mod."github.com/golang/mock"]
    version = "v1.5.0"
    hash = "sha256-DwsajUB1hknylVqmvPyD+z5jjHiP4D+dNv9FUiuYYnU="
  [mod."github.com/golang/protobuf"]
    version = "v1.4.3"
    hash = "sha256-GoytLjWoBKfZq3eBDa4rGQNP2la2IrpkFSWjsH/sPBI="
  [mod."github.com/golang/snappy"]
    version = "v0.0.4"
    hash = "sha256-Umx+5xHAQCN/Gi4HbtMhnDCSPFAXSsjVbXd8n5LhjAA="
  [mod."github.com/gorilla/mux"]
    version = "v1.7.5-0.20200711200521-98cb6bf42e08"
    hash = "sha256-s905hpzMH9bOLue09E2JmzPXfIS4HhAlgT7g13HCwKE="
  [mod."github.com/gosuri/uilive"]
    version = "v0.0.4"
    hash = "sha256-T81PkAKf0kl2jeF4HG0AehaDsGyzW6ZVQyDtSjjonV8="
  [mod."github.com/hashicorp/golang-lru"]
    version = "v0.5.4"
    hash = "sha256-1skUMZX+iIf66J1TBVYGWO1OWwQcaoXut3mne331q+k="
  [mod."github.com/jmespath/go-jmespath"]
    version = "v0.4.0"
    hash = "sha256-xpT9g2qIXmPq7eeHUXHiDqJeQoHCudh44G/KCSFbcuo="
  [mod."github.com/kr/text"]
    version = "v0.2.0"
    hash = "sha256-fadcWxZOORv44oak3jTxm6YcITcFxdGt4bpn869HxUE="
  [mod."github.com/mattn/go-isatty"]
    version = "v0.0.12"
    hash = "sha256-noBpx3K4sa7tJcPpSUh+h7wJ8CRfrObaraKC2dE6VWU="
  [mod."github.com/mattn/go-runewidth"]
    version = "v0.0.10"
    hash = "sha256-S/ppuBSisvWwrRp36vFPN7xAVowYReIY5KySiI1FS2o="
  [mod."github.com/matttproud/golang_protobuf_extensions"]
    version = "v1.0.1"
    hash = "sha256-ystDNStxR90j4CK+AMcEQ5oyYFRgWoGdvWlS0XQMDLQ="
  [mod."github.com/niemeyer/pretty"]
    version = "v0.0.0-20200227124842-a10e7caefd8e"
    hash = "sha256-m2D7hWZrDst0rb91lmjSuNrzBQbmQ0Oe2UOp3wn8qso="
  [mod."github.com/paulbellamy/ratecounter"]
    version = "v0.2.0"
    hash = "sha256-yZGMzwo5Gadrb04WJfVNGzkWYEjtjJ+yvRVtw1QwjHw="
  [mod."github.com/pbnjay/memory"]
    version = "v0.0.0-20190104145345-974d429e7ae4"
    hash = "sha256-eM4qoRupv0Py1TqMn/wSFEDeICuq/twUviDZpm95X00="
  [mod."github.com/peterh/liner"]
    version = "v1.1.0"
    hash = "sha256-YSDIUdBUbtO6Wpf1/zadI/+z3yGlvYP4WHUM68rhPJM="
  [mod."github.com/pierrec/lz4/v4"]
    version = "v4.1.14"
    hash = "sha256-aWHB2H8bmSZ2DK6AXHzR6ODBdWJKwU1Q+14fafrWmqM="
  [mod."github.com/pkg/browser"]
    version = "v0.0.0-20210911075715-681adbf594b8"
    hash = "sha256-JZhcXaILA6QFOYnVdiHbKQuKABQNAE0VhMWZXsZngLQ="
  [mod."github.com/pmezard/go-difflib"]
    version = "v1.0.0"
    hash = "sha256-/FtmHnaGjdvEIKAJtrUfEhV7EVo5A/eYrtdnUkuxLDA="
  [mod."github.com/prometheus/client_golang"]
    version = "v1.7.1"
    hash = "sha256-PBgo8EAcqkRYLyFxR3GKOP/zzNvu7A18uq/FgSVfPEU="
  [mod."github.com/prometheus/client_model"]
    version = "v0.2.0"
    hash = "sha256-LTHxYPRgoggl+v89ly2/RkyPIuJlmZRdGs6ZRtK3zkk="
  [mod."github.com/prometheus/common"]
    version = "v0.10.0"
    hash = "sha256-MYAZJFhir6b2fV8ggC7q9kzIG5h52K7/j+5tq7H7R+U="
  [mod."github.com/prometheus/procfs"]
    version = "v0.1.3"
    hash = "sha256-JJk/ZBGd1ZJep6RFjaS6IZCeDklcSLwkWZ4MtJoDeOc="
  [mod."github.com/rivo/uniseg"]
    version = "v0.1.0"
    hash = "sha256-hfMUzdGA1Ept71D3t++FTM55dwWxN/g7DcvQ0G9glzo="
  [mod."github.com/rs/cors"]
    version = "v1.8.0"
    hash = "sha256-+SW32FBrPDBryzmdN4JrSMjLGbae6WlkMLVUEhUFzh4="
  [mod."github.com/segmentio/ksuid"]
    version = "v1.0.2"
    hash = "sha256-U5qALEwLwGqqC4XwJOHtAA+1AhV1yZqFPS0z/o1KSWI="
  [mod."github.com/stretchr/testify"]
    version = "v1.7.0"
    hash = "sha256-t1I9uCrn9vSUu/z5IZuNyGShmbOcJ6UGc2f75ZBrHzE="
  [mod."github.com/yuin/goldmark"]
    version = "v1.4.13"
    hash = "sha256-GVwFKZY6moIS6I0ZGuio/WtDif+lkZRfqWS6b4AAJyI="
  [mod."go.opentelemetry.io/otel"]
    version = "v0.16.0"
    hash = "sha256-SFXPRsIFR7l1JZVFFvalSUkhwVU+OmZFyruMcPreqhc="
  [mod."go.uber.org/atomic"]
    version = "v1.7.0"
    hash = "sha256-g83RSzO/5k8W3qyiIsrQbVq1F8qJGccdWEXTjkqUOfc="
  [mod."go.uber.org/multierr"]
    version = "v1.6.0"
    hash = "sha256-X+l7OPAkMhpw+5VvFWuQ/DfTCSjQH/8VvSoQrb44CEU="
  [mod."go.uber.org/zap"]
    version = "v1.16.0"
    hash = "sha256-sQSj+Cx++tz78WezoiiSqtGMDXdYdhCoGJELCnwLeB8="
  [mod."golang.org/x/exp"]
    version = "v0.0.0-20220916125017-b168a2c6b86b"
    hash = "sha256-wIoUisHbBvzmS35jk7hw/P4DMxZpitjKFuFSXLXksks="
  [mod."golang.org/x/lint"]
    version = "v0.0.0-20201208152925-83fdc39ff7b5"
    hash = "sha256-g4Z9PREOxGoN7n/XhutawsITBznJlbz6StXeDYvOQ1c="
  [mod."golang.org/x/net"]
    version = "v0.0.0-20220722155237-a158d28d115b"
    hash = "sha256-TccMT2GgC1qKp8Yxk1zShJVvr29GemCqKSNJeYkjLo4="
  [mod."golang.org/x/sync"]
    version = "v0.0.0-20220722155255-886fb9371eb4"
    hash = "sha256-ZZyIlxh+nqsOiWHstW7eHXN7RhHnbSL2eDIzcve07Q0="
  [mod."golang.org/x/sys"]
    version = "v0.0.0-20220722155257-8c9f86f7a55f"
    hash = "sha256-mXgFTb2vfUEjTPA6PX7CZTvKGJWaxoU2QplyI1GjC+w="
  [mod."golang.org/x/term"]
    version = "v0.0.0-20210927222741-03fcf44c2211"
    hash = "sha256-DsX2xay7Y/0/bikp4vU8ArF0B6KHyqEc37PwgvmjhSs="
  [mod."golang.org/x/text"]
    version = "v0.3.7"
    hash = "sha256-XH2pUzzQx95O0rak00grQvfACfL+EmZiV7ZzJBkX+XY="
  [mod."golang.org/x/xerrors"]
    version = "v0.0.0-20200804184101-5ec99f83aff1"
    hash = "sha256-62f++IO8Ia32CYy+xX8XDxCcT9r1sbPvVwoKV99gf7U="
  [mod."google.golang.org/protobuf"]
    version = "v1.25.1-0.20201020201750-d3470999428b"
    hash = "sha256-EBEzVYciYVtjIgkXINHAgWpa2tZRVOwgnwL4c3L0fX8="
  [mod."gopkg.in/check.v1"]
    version = "v1.0.0-20200902074654-038fdea0a05b"
    hash = "sha256-pFro5uj8Nxt1NLLVSSHowWEXFMLv/3xPy/S5FcC/Exg="
  [mod."gopkg.in/natefinch/lumberjack.v2"]
    version = "v2.0.0"
    hash = "sha256-CLir3wRkgNy7tXQWODk7u3RP/W7qIsO2LADdM6/vWtQ="
  [mod."gopkg.in/yaml.v2"]
    version = "v2.4.0"
    hash = "sha256-uVEGglIedjOIGZzHW4YwN1VoRSTK8o0eGZqzd+TNdd0="
  [mod."gopkg.in/yaml.v3"]
    version = "v3.0.1"
    hash = "sha256-FqL9TKYJ0XkNwJFnq9j0VvJ5ZUU1RvH/52h/f5bkYAU="
  [mod."honnef.co/go/tools"]
    version = "v0.1.0"
    hash = "sha256-SURHu55vKbwd9JF0AFS3WLPIkQzQVan6aQTyrP8iwzA="
