schema = 1

[mod]
  [mod."github.com/BurntSushi/toml"]
    version = "v0.3.1"
    hash = "sha256-Rqak1dE/Aj/+Kx1/pl3Hifgt+Q3OzuZ5fJR+/x3nTbo="
  [mod."github.com/OneOfOne/xxhash"]
    version = "v1.2.2"
    hash = "sha256-JvJnJFr9NFh5u+b7BgNEIwZR6scXW8l8RkT1DXmGTtY="
  [mod."github.com/alecthomas/template"]
    version = "v0.0.0-20190718012654-fb15b899a751"
    hash = "sha256-RsS4qxdRQ3q+GejA8D9Iu31A/mZNms4LbJ7518jWiu4="
  [mod."github.com/alecthomas/units"]
    version = "v0.0.0-20190717042225-c3de453c63f4"
    hash = "sha256-vho02JWLkLST8oBHdWufpXZxoDSkCUVkMP6M/eg/Q0s="
  [mod."github.com/apache/thrift"]
    version = "v0.16.0"
    hash = "sha256-4jsjTxU5CZ6feurBx3pIY2JF5FsoMewVOQHeVtgHkdA="
  [mod."github.com/araddon/dateparse"]
    version = "v0.0.0-20210429162001-6b43995a97de"
    hash = "sha256-UuX84naeRGMsFOgIgRoBHG5sNy1CzBkWPKmd6VbLwFw="
  [mod."github.com/armon/consul-api"]
    version = "v0.0.0-20180202201655-eb2c6b5be1b6"
    hash = "sha256-aVqUesaJyU/nrgwlfG2p16VxcF6Hyk4s8diMp0Nuzsg="
  [mod."github.com/aws/aws-sdk-go"]
    version = "v1.36.17"
    hash = "sha256-jUasRPchEoCFbnEAV1k61nxLRP9bynig/qriFeuLhQI="
  [mod."github.com/axiomhq/hyperloglog"]
    version = "v0.0.0-20191112132149-a4c4c47bc57f"
    hash = "sha256-mhThkWjecSomS8pP6uJDYnUq/isLLwhwsENXYKHvkl8="
  [mod."github.com/beorn7/perks"]
    version = "v1.0.1"
    hash = "sha256-h75GUqfwJKngCJQVE5Ao5wnO3cfKD9lSIteoLp/3xJ4="
  [mod."github.com/cespare/xxhash"]
    version = "v1.1.0"
    hash = "sha256-nVDTtXH9PC3yJ0THaQZEN243UP9xgLi/clt5xRqj3+M="
  [mod."github.com/cespare/xxhash/v2"]
    version = "v2.1.1"
    hash = "sha256-cF+sDnnTZ1xRwjsy08SVSV/JoZalwY+dg0Zkghy6BNw="
  [mod."github.com/coreos/etcd"]
    version = "v3.3.10+incompatible"
    hash = "sha256-fCyJRKX9dgcb2JwqiQL/OshS3Ilmm7bY3OCISxZ6l68="
  [mod."github.com/coreos/go-etcd"]
    version = "v2.0.0+incompatible"
    hash = "sha256-Uo5heUPCLTGZ8ns1Zi48kuNnPtvJ/7kLXpMGpT4kY/U="
  [mod."github.com/coreos/go-semver"]
    version = "v0.2.0"
    hash = "sha256-YFZP0mXFl1P1S0udGNP0AlZsfe0sMAy7g6BIbFeJ8L0="
  [mod."github.com/cpuguy83/go-md2man"]
    version = "v1.0.10"
    hash = "sha256-XP8oKAx5LgQ0fO1rjO9tWnbXB431VOzXVaRDPUP900g="
  [mod."github.com/creack/pty"]
    version = "v1.1.9"
    hash = "sha256-Rj6c4/3IApJcS36iPVIEdlMSC/SWmywnpqk1500ik5k="
  [mod."github.com/davecgh/go-spew"]
    version = "v1.1.1"
    hash = "sha256-nhzSUrE1fCkN0+RL04N4h8jWmRFPPPWbCuDc7Ss0akI="
  [mod."github.com/dgryski/go-metro"]
    version = "v0.0.0-20180109044635-280f6062b5bc"
    hash = "sha256-WdJuGgX7NKfocz6IhMcClfx30ZnxAPjfZTRAOr2eAqk="
  [mod."github.com/dgryski/go-rendezvous"]
    version = "v0.0.0-20200823014737-9f7001d12a5f"
    hash = "sha256-n/7xo5CQqo4yLaWMSzSN1Muk/oqK6O5dgDOFWapeDUI="
  [mod."github.com/fraugster/parquet-go"]
    version = "v0.10.1-0.20220222153523-e6b70a8a7212"
    hash = "sha256-eo9iwQHr1ox608jnuoYBtFmKxv923mg+H3KlECv9Iqk="
  [mod."github.com/fsnotify/fsnotify"]
    version = "v1.4.9"
    hash = "sha256-HZBMhbFqcZM9oxSbWqISzEE7GF7JZpco5tyta6c4OcQ="
  [mod."github.com/gin-contrib/sse"]
    version = "v0.1.0"
    hash = "sha256-zYbMTao+1F+385Lvsba9roLmmt9eYqr57sUWo0LCVhw="
  [mod."github.com/gin-gonic/gin"]
    version = "v1.5.0"
    hash = "sha256-nCnxGg6pC1GvzaM/zGcfMkWveSTRb+FJeaE+Z4gcQo4="
  [mod."github.com/go-kit/kit"]
    version = "v0.9.0"
    hash = "sha256-dcW5++iYlt0zxgaZTpWXKl8LX4/npy+MadnXXmzzRUo="
  [mod."github.com/go-logfmt/logfmt"]
    version = "v0.4.0"
    hash = "sha256-qX6aMMNTmN+D7LtQLZxW/LAKxRpze4vO77F2EQLrVRs="
  [mod."github.com/go-playground/locales"]
    version = "v0.12.1"
    hash = "sha256-mwEAA4haqpusvPyIRJCbDD4fFiEVo56HzcZb/eapNp0="
  [mod."github.com/go-playground/universal-translator"]
    version = "v0.16.0"
    hash = "sha256-d5Xk2IIGoU3M84+nbvMJtIe+zVDW457Sh6rgI5Tgogg="
  [mod."github.com/go-redis/redis/v8"]
    version = "v8.4.11"
    hash = "sha256-+xxGAt4fAD8NO+W+CHFNPxqsqd5jIXeAWKRukxUu82o="
  [mod."github.com/go-stack/stack"]
    version = "v1.8.0"
    hash = "sha256-26RlTEcAkbewMUtmirKrDGQ1WJlNousp69v7HMopYnI="
  [mod."github.com/gogo/protobuf"]
    version = "v1.1.1"
    hash = "sha256-AmlVpKOrFGBUTVR7J5grNUlVJ3hiJcHY8nq+jDRV26s="
  [mod."github.com/golang-jwt/jwt"]
    version = "v3.2.1+incompatible"
    hash = "sha256-lRqMYMddv9J5IwqDBjqGmFtLpwwgvq86CkCvJxzM1cw="
  [mod."github.com/golang/mock"]
    version = "v1.5.0"
    hash = "sha256-DwsajUB1hknylVqmvPyD+z5jjHiP4D+dNv9FUiuYYnU="
  [mod."github.com/golang/protobuf"]
    version = "v1.4.3"
    hash = "sha256-GoytLjWoBKfZq3eBDa4rGQNP2la2IrpkFSWjsH/sPBI="
  [mod."github.com/golang/snappy"]
    version = "v0.0.4"
    hash = "sha256-Umx+5xHAQCN/Gi4HbtMhnDCSPFAXSsjVbXd8n5LhjAA="
  [mod."github.com/google/go-cmp"]
    version = "v0.5.4"
    hash = "sha256-kZWs4w9qj+za4xCz++Q9cSZ8aEhG3R9eOU8Iaha/qdE="
  [mod."github.com/google/gofuzz"]
    version = "v1.0.0"
    hash = "sha256-ZvgcSQt4kMwS6nvPp3jrlCHSH3bky1oBD6kytnEa5GM="
  [mod."github.com/google/renameio"]
    version = "v0.1.0"
    hash = "sha256-XQ5yI+LMfFQuK7+T3Xx5jiaRP7GmiQSsPkFmm1TpIs4="
  [mod."github.com/gorilla/mux"]
    version = "v1.7.5-0.20200711200521-98cb6bf42e08"
    hash = "sha256-s905hpzMH9bOLue09E2JmzPXfIS4HhAlgT7g13HCwKE="
  [mod."github.com/gosuri/uilive"]
    version = "v0.0.4"
    hash = "sha256-T81PkAKf0kl2jeF4HG0AehaDsGyzW6ZVQyDtSjjonV8="
  [mod."github.com/hashicorp/golang-lru"]
    version = "v0.5.4"
    hash = "sha256-1skUMZX+iIf66J1TBVYGWO1OWwQcaoXut3mne331q+k="
  [mod."github.com/hashicorp/hcl"]
    version = "v1.0.0"
    hash = "sha256-xsRCmYyBfglMxeWUvTZqkaRLSW+V2FvNodEDjTGg1WA="
  [mod."github.com/hpcloud/tail"]
    version = "v1.0.0"
    hash = "sha256-7ByBr/RcOwIsGPCiCUpfNwUSvU18QAY+HMnCJr8uU1w="
  [mod."github.com/inconshreveable/mousetrap"]
    version = "v1.0.0"
    hash = "sha256-ogTuLrV40FwS4ueo4hh6hi1wPywOI+LyIqfNjsibwNY="
  [mod."github.com/influxdata/influxdb"]
    version = "v1.7.6"
    hash = "sha256-XlzcI1Jm0ctyKLqYp40kPGOiW7pVlbzu7VJJVOEH00Y="
  [mod."github.com/jmespath/go-jmespath"]
    version = "v0.4.0"
    hash = "sha256-xpT9g2qIXmPq7eeHUXHiDqJeQoHCudh44G/KCSFbcuo="
  [mod."github.com/jmespath/go-jmespath/internal/testify"]
    version = "v1.5.1"
    hash = "sha256-eOjXyGv7P1x+iO9rPrmAGvNj2JH5p36OgSiVyJv/hyI="
  [mod."github.com/json-iterator/go"]
    version = "v1.1.10"
    hash = "sha256-jdS2C0WsgsWREBSj+YUzSqdZofMfUMecaOQ/lB9Mu6k="
  [mod."github.com/julienschmidt/httprouter"]
    version = "v1.2.0"
    hash = "sha256-xhj9PYKNIfQ/CQb8/3O3OtBmiIAJYtiL23cTnRj1C80="
  [mod."github.com/kisielk/gotool"]
    version = "v1.0.0"
    hash = "sha256-lsdQkue8gFz754PGqczUnvGiCQq87SruQtdrDdQVTpE="
  [mod."github.com/konsorten/go-windows-terminal-sequences"]
    version = "v1.0.1"
    hash = "sha256-Nwp+Cza9dIu3ogVGip6wyOjWwwaq+2hU3eYIe4R7kNE="
  [mod."github.com/kr/logfmt"]
    version = "v0.0.0-20140226030751-b84e30acd515"
    hash = "sha256-CePQbqWGtS8qP/Av9pkLiqZwH6RaZQff/s1l+1//jQo="
  [mod."github.com/kr/pretty"]
    version = "v0.1.0"
    hash = "sha256-Fx+TaNrxW0VfzonT2jnd5MU09RRz7GJZkqAtJR6/pKI="
  [mod."github.com/kr/pty"]
    version = "v1.1.1"
    hash = "sha256-AVeS+ivwNzIrgWQaLtsmO2f2MYGpxIVqdac/EzaYI1Q="
  [mod."github.com/kr/text"]
    version = "v0.2.0"
    hash = "sha256-fadcWxZOORv44oak3jTxm6YcITcFxdGt4bpn869HxUE="
  [mod."github.com/leodido/go-urn"]
    version = "v1.1.0"
    hash = "sha256-BW9BrvDAyKSbbh149UvHlxaX/UuTtoaoHywhKlVEZbk="
  [mod."github.com/magiconair/properties"]
    version = "v1.8.0"
    hash = "sha256-tkt1yGEPbRjQvhsCkiD7jyLyhX2eo4AWx0ihzYUZIKg="
  [mod."github.com/mattn/go-isatty"]
    version = "v0.0.12"
    hash = "sha256-noBpx3K4sa7tJcPpSUh+h7wJ8CRfrObaraKC2dE6VWU="
  [mod."github.com/mattn/go-runewidth"]
    version = "v0.0.10"
    hash = "sha256-S/ppuBSisvWwrRp36vFPN7xAVowYReIY5KySiI1FS2o="
  [mod."github.com/matttproud/golang_protobuf_extensions"]
    version = "v1.0.1"
    hash = "sha256-ystDNStxR90j4CK+AMcEQ5oyYFRgWoGdvWlS0XQMDLQ="
  [mod."github.com/mitchellh/go-homedir"]
    version = "v1.1.0"
    hash = "sha256-oduBKXHAQG8X6aqLEpqZHs5DOKe84u6WkBwi4W6cv3k="
  [mod."github.com/mitchellh/mapstructure"]
    version = "v1.1.2"
    hash = "sha256-OU9HZYHtl0qaqMFd84w7snkkRuRY6UMSsfCnL5HYdw0="
  [mod."github.com/modern-go/concurrent"]
    version = "v0.0.0-20180306012644-bacd9c7ef1dd"
    hash = "sha256-OTySieAgPWR4oJnlohaFTeK1tRaVp/b0d1rYY8xKMzo="
  [mod."github.com/modern-go/reflect2"]
    version = "v1.0.1"
    hash = "sha256-5D1HGVBc/REwPVdlPYcXsbZM80OIh7V5uiyKAbMA5qo="
  [mod."github.com/mwitkow/go-conntrack"]
    version = "v0.0.0-20161129095857-cc309e4a2223"
    hash = "sha256-rgZ2fm0Vi04xGDhkeFPDSZ+KPKi0a/5rerjOdea1eVk="
  [mod."github.com/niemeyer/pretty"]
    version = "v0.0.0-20200227124842-a10e7caefd8e"
    hash = "sha256-m2D7hWZrDst0rb91lmjSuNrzBQbmQ0Oe2UOp3wn8qso="
  [mod."github.com/nxadm/tail"]
    version = "v1.4.4"
    hash = "sha256-S336Q+5j2uVmwLOfEUpU0iFBEEDH+UtdQO0NWPsc9OY="
  [mod."github.com/onsi/ginkgo"]
    version = "v1.14.2"
    hash = "sha256-VRSl25r2U6WJ5MSN5OFO2RI1UEpGUARNPv5J4KVsaWw="
  [mod."github.com/onsi/gomega"]
    version = "v1.10.4"
    hash = "sha256-5u1GaACc0OUa8itTbcGUzLKmAb04IbbpqQYz5ldZiY8="
  [mod."github.com/paulbellamy/ratecounter"]
    version = "v0.2.0"
    hash = "sha256-yZGMzwo5Gadrb04WJfVNGzkWYEjtjJ+yvRVtw1QwjHw="
  [mod."github.com/pbnjay/memory"]
    version = "v0.0.0-20190104145345-974d429e7ae4"
    hash = "sha256-eM4qoRupv0Py1TqMn/wSFEDeICuq/twUviDZpm95X00="
  [mod."github.com/pelletier/go-toml"]
    version = "v1.2.0"
    hash = "sha256-Yt9MGTbIaU/1FhE7SO5UCQbTLxe+2vsypTdf38i3kFY="
  [mod."github.com/peterh/liner"]
    version = "v1.1.0"
    hash = "sha256-YSDIUdBUbtO6Wpf1/zadI/+z3yGlvYP4WHUM68rhPJM="
  [mod."github.com/pierrec/lz4/v4"]
    version = "v4.1.14"
    hash = "sha256-aWHB2H8bmSZ2DK6AXHzR6ODBdWJKwU1Q+14fafrWmqM="
  [mod."github.com/pkg/browser"]
    version = "v0.0.0-20210911075715-681adbf594b8"
    hash = "sha256-JZhcXaILA6QFOYnVdiHbKQuKABQNAE0VhMWZXsZngLQ="
  [mod."github.com/pkg/errors"]
    version = "v0.9.1"
    hash = "sha256-mNfQtcrQmu3sNg/7IwiieKWOgFQOVVe2yXgKBpe/wZw="
  [mod."github.com/pmezard/go-difflib"]
    version = "v1.0.0"
    hash = "sha256-/FtmHnaGjdvEIKAJtrUfEhV7EVo5A/eYrtdnUkuxLDA="
  [mod."github.com/prometheus/client_golang"]
    version = "v1.7.1"
    hash = "sha256-PBgo8EAcqkRYLyFxR3GKOP/zzNvu7A18uq/FgSVfPEU="
  [mod."github.com/prometheus/client_model"]
    version = "v0.2.0"
    hash = "sha256-LTHxYPRgoggl+v89ly2/RkyPIuJlmZRdGs6ZRtK3zkk="
  [mod."github.com/prometheus/common"]
    version = "v0.10.0"
    hash = "sha256-MYAZJFhir6b2fV8ggC7q9kzIG5h52K7/j+5tq7H7R+U="
  [mod."github.com/prometheus/procfs"]
    version = "v0.1.3"
    hash = "sha256-JJk/ZBGd1ZJep6RFjaS6IZCeDklcSLwkWZ4MtJoDeOc="
  [mod."github.com/rivo/uniseg"]
    version = "v0.1.0"
    hash = "sha256-hfMUzdGA1Ept71D3t++FTM55dwWxN/g7DcvQ0G9glzo="
  [mod."github.com/rogpeppe/go-internal"]
    version = "v1.3.0"
    hash = "sha256-JgiasZeXDy10syy7wmXtqRffDY7CJ1o5VNY+FmmAjVU="
  [mod."github.com/rs/cors"]
    version = "v1.8.0"
    hash = "sha256-+SW32FBrPDBryzmdN4JrSMjLGbae6WlkMLVUEhUFzh4="
  [mod."github.com/russross/blackfriday"]
    version = "v1.5.2"
    hash = "sha256-7MjJB7KZoNFTBo5Qzc3LL9QKrzWf9keqt5lh7tl360s="
  [mod."github.com/scylladb/termtables"]
    version = "v0.0.0-20191203121021-c4c0b6d42ff4"
    hash = "sha256-2axV5I4HdOOuR/iQlok6gqo9lfVquOGIU7KcY9WgP6E="
  [mod."github.com/segmentio/ksuid"]
    version = "v1.0.2"
    hash = "sha256-U5qALEwLwGqqC4XwJOHtAA+1AhV1yZqFPS0z/o1KSWI="
  [mod."github.com/sirupsen/logrus"]
    version = "v1.4.2"
    hash = "sha256-3QzWUsapCmg3F7JqUuINT3/UG097uzLff6iCcCgQ43o="
  [mod."github.com/spaolacci/murmur3"]
    version = "v0.0.0-20180118202830-f09979ecbc72"
    hash = "sha256-RWD4PPrlAsZZ8Xy356MBxpj+/NZI7w2XOU14Ob7/Y9M="
  [mod."github.com/spf13/afero"]
    version = "v1.1.2"
    hash = "sha256-00yWOvw9GosWm6QkogM8MxpnVFRm/7BcdBLG4pQjO1Y="
  [mod."github.com/spf13/cast"]
    version = "v1.3.0"
    hash = "sha256-hbVF7F0YsgSybYEJa7W+Rz0As6OpgmpZOxB5JLFzAXc="
  [mod."github.com/spf13/cobra"]
    version = "v0.0.5"
    hash = "sha256-YovRLduyDxoYoz1tNVgh9rnebjFIaeNeeBzWYrREnXw="
  [mod."github.com/spf13/jwalterweatherman"]
    version = "v1.0.0"
    hash = "sha256-KLftz+gaA5wSkvLqvQ7CuboB79kKEoTJvgTtrXatbiQ="
  [mod."github.com/spf13/pflag"]
    version = "v1.0.5"
    hash = "sha256-w9LLYzxxP74WHT4ouBspH/iQZXjuAh2WQCHsuvyEjAw="
  [mod."github.com/spf13/viper"]
    version = "v1.3.2"
    hash = "sha256-8I/LyWr7cOKg+0NokEbewJ8WNz8hp0KLUW0WgNyGSaA="
  [mod."github.com/stretchr/objx"]
    version = "v0.1.1"
    hash = "sha256-HdGVZCuy7VprC5W9UxGbDmXqsKADMjpEDht7ilGVLco="
  [mod."github.com/stretchr/testify"]
    version = "v1.7.0"
    hash = "sha256-t1I9uCrn9vSUu/z5IZuNyGShmbOcJ6UGc2f75ZBrHzE="
  [mod."github.com/ugorji/go"]
    version = "v1.1.7"
    hash = "sha256-k9HKvzLh9r6Q4l0q5kyeDgc0rnH1VxqmY4EPiFyNL40="
  [mod."github.com/ugorji/go/codec"]
    version = "v1.1.7"
    hash = "sha256-fulAoEEqegVZP4qtPJAD6/vw/AeI00i27tslP2c/7ko="
  [mod."github.com/xordataexchange/crypt"]
    version = "v0.0.3-0.20170626215501-b2862e3d0a77"
    hash = "sha256-HuXuIK/V5iNuF7j68acNQ3SW7rrn1efaI/Rfq0xBAxM="
  [mod."github.com/yuin/goldmark"]
    version = "v1.2.1"
    hash = "sha256-vrL87IsRgYTTHvCH2fodVu+ECk9UCu4kuCy3Ypy2Oos="
  [mod."go.opentelemetry.io/otel"]
    version = "v0.16.0"
    hash = "sha256-SFXPRsIFR7l1JZVFFvalSUkhwVU+OmZFyruMcPreqhc="
  [mod."go.uber.org/atomic"]
    version = "v1.7.0"
    hash = "sha256-g83RSzO/5k8W3qyiIsrQbVq1F8qJGccdWEXTjkqUOfc="
  [mod."go.uber.org/multierr"]
    version = "v1.6.0"
    hash = "sha256-X+l7OPAkMhpw+5VvFWuQ/DfTCSjQH/8VvSoQrb44CEU="
  [mod."go.uber.org/tools"]
    version = "v0.0.0-20190618225709-2cfd321de3ee"
    hash = "sha256-vLL9lT4iMxODR5+I6ZS14V4WcEd7REPNYZt0pCdNKLM="
  [mod."go.uber.org/zap"]
    version = "v1.16.0"
    hash = "sha256-sQSj+Cx++tz78WezoiiSqtGMDXdYdhCoGJELCnwLeB8="
  [mod."golang.org/x/crypto"]
    version = "v0.0.0-20200622213623-75b288015ac9"
    hash = "sha256-QvFbJEm3gXs2NtaaREbkbAtdHpU4fqX+0C0EvTezdKM="
  [mod."golang.org/x/lint"]
    version = "v0.0.0-20201208152925-83fdc39ff7b5"
    hash = "sha256-g4Z9PREOxGoN7n/XhutawsITBznJlbz6StXeDYvOQ1c="
  [mod."golang.org/x/mod"]
    version = "v0.4.0"
    hash = "sha256-evN3gLblJMWsyndKzPSY8CZ70RmJyuS4glIx8rXBCHg="
  [mod."golang.org/x/net"]
    version = "v0.0.0-20201224014010-6772e930b67b"
    hash = "sha256-z+sVfY3Adi8HLla0PLjjVbeIRhST+XipZpeVPnxq0HI="
  [mod."golang.org/x/sync"]
    version = "v0.0.0-20201020160332-67f06af15bc9"
    hash = "sha256-hfvviA1/duBMtleic86KvYNlUz3/V7XKVAggZtUldyQ="
  [mod."golang.org/x/sys"]
    version = "v0.0.0-20210616045830-e2b7044e8c71"
    hash = "sha256-fCDPkRvIVR+TXPTG3RDz+c3qUr+fWgccZmOAvuAMe4o="
  [mod."golang.org/x/term"]
    version = "v0.0.0-20210317153231-de623e64d2a6"
    hash = "sha256-LH4/pPdtJenAAZCupEX0xR4b1FJ/xXZ6JBuidnC03Ys="
  [mod."golang.org/x/text"]
    version = "v0.3.4"
    hash = "sha256-si28LUeDO14RbU4ZAEYNB3XdClrBvFxy2EIDcgXlB70="
  [mod."golang.org/x/tools"]
    version = "v0.1.0"
    hash = "sha256-ZdYPAsjyRell05igc953KzTL4mWrYNS0LufGdJRw3RI="
  [mod."golang.org/x/xerrors"]
    version = "v0.0.0-20200804184101-5ec99f83aff1"
    hash = "sha256-62f++IO8Ia32CYy+xX8XDxCcT9r1sbPvVwoKV99gf7U="
  [mod."google.golang.org/protobuf"]
    version = "v1.25.1-0.20201020201750-d3470999428b"
    hash = "sha256-EBEzVYciYVtjIgkXINHAgWpa2tZRVOwgnwL4c3L0fX8="
  [mod."gopkg.in/alecthomas/kingpin.v2"]
    version = "v2.2.6"
    hash = "sha256-uViE2kPj7tMrGYVjjdLOl2jFDmmu+3P7GvnZBse2zVY="
  [mod."gopkg.in/check.v1"]
    version = "v1.0.0-20200902074654-038fdea0a05b"
    hash = "sha256-pFro5uj8Nxt1NLLVSSHowWEXFMLv/3xPy/S5FcC/Exg="
  [mod."gopkg.in/errgo.v2"]
    version = "v2.1.0"
    hash = "sha256-Ir/MuxQFxvVJEciovGOZbM8ZfKJ/AYotPwYfH2FctRg="
  [mod."gopkg.in/fsnotify.v1"]
    version = "v1.4.7"
    hash = "sha256-j/Ts92oXa3k1MFU7Yd8/AqafRTsFn7V2pDKCyDJLah8="
  [mod."gopkg.in/go-playground/assert.v1"]
    version = "v1.2.1"
    hash = "sha256-9SYLM6GItl90ggSFWIGK5dxS3siUpmAilw2oO/2risA="
  [mod."gopkg.in/go-playground/validator.v9"]
    version = "v9.29.1"
    hash = "sha256-q73DVsqbXK7kChfwztEhT90vi6fLUezdfXwIJcsmENo="
  [mod."gopkg.in/natefinch/lumberjack.v2"]
    version = "v2.0.0"
    hash = "sha256-CLir3wRkgNy7tXQWODk7u3RP/W7qIsO2LADdM6/vWtQ="
  [mod."gopkg.in/tomb.v1"]
    version = "v1.0.0-20141024135613-dd632973f1e7"
    hash = "sha256-W/4wBAvuaBFHhowB67SZZfXCRDp5tzbYG4vo81TAFdM="
  [mod."gopkg.in/yaml.v2"]
    version = "v2.4.0"
    hash = "sha256-uVEGglIedjOIGZzHW4YwN1VoRSTK8o0eGZqzd+TNdd0="
  [mod."gopkg.in/yaml.v3"]
    version = "v3.0.1"
    hash = "sha256-FqL9TKYJ0XkNwJFnq9j0VvJ5ZUU1RvH/52h/f5bkYAU="
  [mod."honnef.co/go/tools"]
    version = "v0.1.0"
    hash = "sha256-SURHu55vKbwd9JF0AFS3WLPIkQzQVan6aQTyrP8iwzA="
