# nvfetcher.toml
[broker-to-json]
src.github = "grigorescu/broker-to-json"
fetch.github = "grigorescu/broker-to-json"

[aim]
src.github = "aimhubio/aim"
fetch.github = "aimhubio/aim"

[vailyn]
src.github = "VainlyStrain/Vailyn"
fetch.github = "VainlyStrain/Vailyn"

[sslproxy]
src.git = "https://github.com/sonertari/SSLproxy"
fetch.github = "sonertari/SSLproxy"

[sybilhunter]
src.git = "https://github.com/NullHypothesis/sybilhunter"
fetch.github = "NullHypothesis/sybilhunter"

[eZeeKonfigurator]
src.git = "https://github.com/esnet/eZeeKonfigurator"
fetch.github = "esnet/eZeeKonfigurator"

[eZeeKonfigurator_client]
src.git = "https://github.com/esnet/eZeeKonfigurator_client"
fetch.github = "esnet/eZeeKonfigurator_client"

[elastalert2]
src.git = "https://github.com/jertel/elastalert2"
fetch.github = "jertel/elastalert2"

[choochoo]
src.git = "https://github.com/andrewcooke/choochoo"
fetch.github = "andrewcooke/choochoo"

#################
# Python fastai #
#################
[fastai]
src.git = "https://github.com/fastai/fastai"
fetch.github = "fastai/fastai"

[zeekscript]
src.git = "https://github.com/zeek/zeekscript/"
fetch.github = "zeek/zeekscript"
git.fetchSubmodules = true

[py-tree-sitter]
src.git = "https://github.com/tree-sitter/py-tree-sitter"
fetch.github = "tree-sitter/py-tree-sitter"
git.fetchSubmodules = true

[fastcore]
src.git = "https://github.com/fastai/fastcore"
fetch.github = "fastai/fastcore"

[fastprogress]
src.pypi = "fastprogress"
fetch.pypi = "fastprogress"

[zat]
src.git = "https://github.com/SuperCowPowers/zat"
fetch.github = "SuperCowPowers/zat"

[vault-cli]
src.git = "https://github.com/peopledoc/vault-cli"
fetch.github = "peopledoc/vault-cli"

[zed]
src.git = "https://github.com/brimdata/zed"
fetch.github = "brimdata/zed"

[cliche]
src.git = "https://github.com/kootenpv/cliche"
fetch.github = "kootenpv/cliche"

#Python Packages
[btest]
src.pypi = "btest"
fetch.pypi = "btest"

[durationpy]
src.pypi = "durationpy"
fetch.pypi = "durationpy"

