["github.com/BurntSushi/toml"]
  sumVersion = "v0.3.1"
  ["github.com/BurntSushi/toml".fetch]
    type = "git"
    url = "https://github.com/BurntSushi/toml"
    rev = "3012a1dbe2e4bd1391d42b32f0577cb7bbc7f005"
    sha256 = "1fjdwwfzyzllgiwydknf1pwjvy49qxfsczqx5gz3y0izs7as99j6"

["github.com/Songmu/prompter"]
  sumVersion = "v0.4.0"
  ["github.com/Songmu/prompter".fetch]
    type = "git"
    url = "https://github.com/Songmu/prompter"
    rev = "96d843eff47d8adc85c8aafbf9c368a8b7152717"
    sha256 = "038fwfbizg8k4hdq0zq76i4cq1pg03fsnb2368w1ldb6yyl5znqc"

["github.com/andreyvit/diff"]
  sumVersion = "v0.0.0-20170406064948-c7f18ee00883"
  ["github.com/andreyvit/diff".fetch]
    type = "git"
    url = "https://github.com/andreyvit/diff"
    rev = "c7f18ee00883bfd3b00e0a2bf7607827e0148ad4"
    sha256 = "1s4qjkxig5yqahpzfl4xqh4kzi9mymdpkzq6kj3f4dr5dl3hlynr"

["github.com/cpuguy83/go-md2man/v2"]
  sumVersion = "v2.0.0"
  ["github.com/cpuguy83/go-md2man/v2".fetch]
    type = "git"
    url = "https://github.com/cpuguy83/go-md2man"
    rev = "f79a8a8ca69da163eee19ab442bedad7a35bba5a"
    sha256 = "0r1f7v475dxxgzqci1mxfliwadcrk86ippflx9n411325l4g3ghv"

["github.com/davecgh/go-spew"]
  sumVersion = "v1.1.0"
  ["github.com/davecgh/go-spew".fetch]
    type = "git"
    url = "https://github.com/davecgh/go-spew"
    rev = "346938d642f2ec3594ed81d874461961cd0faa76"
    sha256 = "0d4jfmak5p6lb7n2r6yvf5p1zcw0l8j74kn55ghvr7zr7b7axm6c"

["github.com/daviddengcn/go-colortext"]
  sumVersion = "v0.0.0-20180409174941-186a3d44e920"
  ["github.com/daviddengcn/go-colortext".fetch]
    type = "git"
    url = "https://github.com/daviddengcn/go-colortext"
    rev = "186a3d44e9200d7eb331356ca4864f52708e1399"
    sha256 = "18piv4zzcb8abbc7fllz9p6rd4zhsy1gc6iygym381caggmmgxgk"

["github.com/dustin/go-humanize"]
  sumVersion = "v1.0.0"
  ["github.com/dustin/go-humanize".fetch]
    type = "git"
    url = "https://github.com/dustin/go-humanize"
    rev = "9f541cc9db5d55bce703bd99987c9d5cb8eea45e"
    sha256 = "1kqf1kavdyvjk7f8kx62pnm7fbypn9z1vbf8v2qdh3y7z7a0cbl3"

["github.com/golangplus/bytes"]
  sumVersion = "v0.0.0-20160111154220-45c989fe5450"
  ["github.com/golangplus/bytes".fetch]
    type = "git"
    url = "https://github.com/golangplus/bytes"
    rev = "45c989fe545070ef7c9003cf1998bb195c61731a"
    sha256 = "1fpwg1idakpbvkmk8j8yyhv9g7mhr9c922kvff6kj4br4k05zyzr"

["github.com/golangplus/fmt"]
  sumVersion = "v0.0.0-20150411045040-2a5d6d7d2995"
  ["github.com/golangplus/fmt".fetch]
    type = "git"
    url = "https://github.com/golangplus/fmt"
    rev = "2a5d6d7d2995baf7d847b7f16ac0179c6888d37b"
    sha256 = "1242q05qnawhv0klzy1pbq63q8jxkms5hc7421992hzq2m40k5yn"

["github.com/golangplus/testing"]
  sumVersion = "v0.0.0-20180327235837-af21d9c3145e"
  ["github.com/golangplus/testing".fetch]
    type = "git"
    url = "https://github.com/golangplus/testing"
    rev = "af21d9c3145e9c670ea7eb7fc85456c1449edf1c"
    sha256 = "1g83sjvcavqbh92vyirc48mrqd18yfci08zya0hrgk840cr94czc"

["github.com/mattn/go-isatty"]
  sumVersion = "v0.0.11"
  ["github.com/mattn/go-isatty".fetch]
    type = "git"
    url = "https://github.com/mattn/go-isatty"
    rev = "31745d66dd679ac0ac4f8d3ecff168fce6170c6a"
    sha256 = "0h671sv7hfprja495kavazkalkx7xzaqksjh13brcnwq67ijrali"

["github.com/motemen/go-gitconfig"]
  sumVersion = "v0.0.0-20160409144229-d53da5028b75"
  ["github.com/motemen/go-gitconfig".fetch]
    type = "git"
    url = "https://github.com/motemen/go-gitconfig"
    rev = "d53da5028b7583fbacfb1945f4f54e01859b8cc2"
    sha256 = "0anijyjx2dsccwm34p9jfjslc3gfdvg57d7yf7ivvambcydf4h0a"

["github.com/pmezard/go-difflib"]
  sumVersion = "v1.0.0"
  ["github.com/pmezard/go-difflib".fetch]
    type = "git"
    url = "https://github.com/pmezard/go-difflib"
    rev = "792786c7400a136282c1664665ae0a8db921c6c2"
    sha256 = "0c1cn55m4rypmscgf0rrb88pn58j3ysvc2d0432dp3c6fqg6cnzw"

["github.com/russross/blackfriday/v2"]
  sumVersion = "v2.0.1"
  ["github.com/russross/blackfriday/v2".fetch]
    type = "git"
    url = "https://github.com/russross/blackfriday"
    rev = "d3b5b032dc8e8927d31a5071b56e14c89f045135"
    sha256 = "0nlz7isdd4rgnwzs68499hlwicxz34j2k2a0b8jy0y7ycd2bcr5j"

["github.com/sergi/go-diff"]
  sumVersion = "v1.0.0"
  ["github.com/sergi/go-diff".fetch]
    type = "git"
    url = "https://github.com/sergi/go-diff"
    rev = "1744e2970ca51c86172c8190fadad617561ed6e7"
    sha256 = "0swiazj8wphs2zmk1qgq75xza6m19snif94h2m6fi8dqkwqdl7c7"

["github.com/shurcooL/sanitized_anchor_name"]
  sumVersion = "v1.0.0"
  ["github.com/shurcooL/sanitized_anchor_name".fetch]
    type = "git"
    url = "https://github.com/shurcooL/sanitized_anchor_name"
    rev = "7bfe4c7ecddb3666a94b053b422cdd8f5aaa3615"
    sha256 = "1gv9p2nr46z80dnfjsklc6zxbgk96349sdsxjz05f3z6wb6m5l8f"

["github.com/stretchr/objx"]
  sumVersion = "v0.1.0"
  ["github.com/stretchr/objx".fetch]
    type = "git"
    url = "https://github.com/stretchr/objx"
    rev = "facf9a85c22f48d2f52f2380e4efce1768749a89"
    sha256 = "19ynspzjdynbi85xw06mh8ad5j0qa1vryvxjgvbnyrr8rbm4vd8w"

["github.com/stretchr/testify"]
  sumVersion = "v1.3.0"
  ["github.com/stretchr/testify".fetch]
    type = "git"
    url = "https://github.com/stretchr/testify"
    rev = "ffdc059bfe9ce6a4e144ba849dbedead332c6053"
    sha256 = "0wjchp2c8xbgcbbq32w3kvblk6q6yn533g78nxl6iskq6y95lxsy"

["github.com/urfave/cli"]
  sumVersion = "v1.22.4"
  ["github.com/urfave/cli".fetch]
    type = "git"
    url = "https://github.com/urfave/cli"
    rev = "053ba9dd02d2bfb768da2c1c50370c59d41dc04b"
    sha256 = "1s7frsmiih4wh8vpx9z3ck4667c6vpjrmba7b9ymnv1p9khyg8wc"

["golang.org/x/crypto"]
  sumVersion = "v0.0.0-20191219195013-becbf705a915"
  ["golang.org/x/crypto".fetch]
    type = "git"
    url = "https://go.googlesource.com/crypto"
    rev = "becbf705a91575484002d598f87d74f0002801e7"
    sha256 = "19si50189jjq53mcs89ag380s30xrnd0m61dn948p015dlsznmrx"

["golang.org/x/net"]
  sumVersion = "v0.0.0-20190404232315-eb5bcb51f2a3"
  ["golang.org/x/net".fetch]
    type = "git"
    url = "https://go.googlesource.com/net"
    rev = "eb5bcb51f2a31c7d5141d810b70815c05d9c9146"
    sha256 = "17k4g8krxbl84gzcs275b7gsh66dzm15fdxivjnx9xz8q84l4kby"

["golang.org/x/sys"]
  sumVersion = "v0.0.0-20191220220014-0732a990476f"
  ["golang.org/x/sys".fetch]
    type = "git"
    url = "https://go.googlesource.com/sys"
    rev = "0732a990476f7f2f5f7200b39ba4ab730c0f09f8"
    sha256 = "0qpkf2aaz5nrd47q7bibiyh07saamqj8yn104ck3ghslp0mjikf3"

["golang.org/x/text"]
  sumVersion = "v0.3.0"
  ["golang.org/x/text".fetch]
    type = "git"
    url = "https://go.googlesource.com/text"
    rev = "f21a4dfb5e38f5895301dc265a8def02365cc3d0"
    sha256 = "0r6x6zjzhr8ksqlpiwm5gdd7s209kwk5p4lw54xjvz10cs3qlq19"

["gopkg.in/check.v1"]
  sumVersion = "v0.0.0-20161208181325-20d25e280405"
  ["gopkg.in/check.v1".fetch]
    type = "git"
    url = "https://gopkg.in/check.v1"
    rev = "20d25e2804050c1cd24a7eea1e7a6447dd0e74ec"
    sha256 = "0k1m83ji9l1a7ng8a7v40psbymxasmssbrrhpdv2wl4rhs0nc3np"

["gopkg.in/yaml.v2"]
  sumVersion = "v2.2.2"
  ["gopkg.in/yaml.v2".fetch]
    type = "git"
    url = "https://gopkg.in/yaml.v2"
    rev = "51d6538a90f86fe93ac480b35f37b2be17fef232"
    sha256 = "01wj12jzsdqlnidpyjssmj0r4yavlqy7dwrg7adqd8dicjc4ncsa"
