[devshell]
packages = ["gomod2nix"]

[[commands]]
name = "t1"
category = "test"
command = '''
        source $PRJ_ROOT/packages/update.sh
        mkcd
'''
help = ""
[[commands]]
name = "zed-update"
category = "update"
command = '''
        git clone https://github.com/brimdata/zed --depth=1 /tmp/zed
        gomod2nix -dir /tmp/zed
        cp -rf /tmp/zed/gomod2nix.toml $PRJ_ROOT/packages/pkgs/zed
        '''
help = "gomod2nix to zed"
