name: "CI"
on:
  pull_request:
  push:
  schedule:
    - cron: "0 0 * * SAT" # every sunday

jobs:
  nix-tests:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v2.4.0
        with:
          fetch-depth: 0

      - uses: cachix/install-nix-action@v16
        with:
          install_url: https://github.com/numtide/nix-unstable-installer/releases/download/nix-2.6.0pre20220106_f71d846/install
          extra_nix_config: |
            experimental-features = nix-command flakes
            system-features = nixos-test benchmark big-parallel kvm recursive-nix

      - uses: cachix/cachix-action@v10
        with:
          name: zeek
          pushFilter: '(-source$|\.tar\.gz$|\.squashfs$)'
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"

      # CI workflows
      - name: Run Nix Format Check
        run: nix -Lv develop -c nixpkgs-fmt --check .

      - name: Run Nix Flake Show
        run: |
          nix develop -c only-x86-64_linux
          nix flake show

      - name: Run Nix Flake Check
        run: |
          nix -Lv flake check
          git reset --hard

      - name: Run nvfetcher-github
        run: |
          nix develop -c -- update nvfetcher ./packages/sources.toml

      - name: bumpup commands
        run: |
          nix -Lv develop -c update gomod2nix
      - name: Build Packages
        run: |
          nix -Lv build .\#broker
          nix -Lv build .\#elastalert2
          nix -Lv build .\#zat
          nix -Lv build .\#zed
          nix -Lv build .\#btest

      - name: Build microvm kernel
        run: |
          nix build .\#microvm-kernel

      - name: Check Osquery-vm-systemd
        run: |
          nix build .\#osquery-bin.tests.osquery-vm-systemd

      - name: Build Package GoPackages
        run: |
          nix -Lv build .\#gst
          nix -Lv build .\#ghq

      - name: Commit changes
        if: ${{ env.COMMIT_MSG != null }}
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: ${{ env.COMMIT_MSG }}
